project_name: keycatd
before:
  hooks:
    - make static
    - make autogen
builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/keycatd
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - '386'
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm64
archives:
  -
    id: keycatd
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}" 
checksum:
  name_template: 'checksums.txt'
release:
  github:
    owner: keydotcat
    name: keycatd
dockers:
  - goos: linux
    goarch: amd64
    binaries: 
      - keycatd
    image_templates:
      - 'keycat/keycatd:{{ .Tag }}'
      - 'keycat/keycatd:latest'
    extra_files:
    - keycatd.toml
